Repository TiiaSelin/slowrun, pull requests merged in 2025-09, with the labels that each got.

#7 Testejä
  .github/workflows/pr_test.yml
  .gitignore
  requirements.txt
  slowrun/urls.py
  uutiset/tests.py
  uutiset/tests/__init__.py
  uutiset/tests/test_views.py
Labels: testing

#13 Arvoportaat
  static/index.html
  static/styles/style-computer.css
  static/styles/style-mobile.css
Labels: enhancement

#11 en saa mobiilinäkymän karttaa oikean korkuiseksi
  static/styles/style-mobile.css
Labels: help wanted

#18 Luotu malli uutisobjektille ja lisätty tarvittavat asetukset.
  .gitignore
  requirements.txt
  slowrun/settings.py
  slowrun/urls.py
  uutiset/admin.py
  uutiset/migrations/0001_initial.py
  uutiset/models.py
Labels: enhancement

#19 Kontaktilomake
  kontaktilomake/__init__.py
  kontaktilomake/admin.py
  kontaktilomake/apps.py
  kontaktilomake/migrations/0001_initial.py
  kontaktilomake/migrations/0002_rename_aihe_viesti_paikkakunta.py
  kontaktilomake/migrations/__init__.py
  kontaktilomake/models.py
  kontaktilomake/templates/index.html
  kontaktilomake/tests.py
  kontaktilomake/urls.py
  kontaktilomake/views.py
  slowrun/settings.py
  slowrun/urls.py
  uutiset/tests/test_views.py
Labels: enhancement

#22 Moar tests
  manage.py
  slowrun/urls.py
  uutiset/tests/test_views.py
  uutiset/tests/test_views_models.py
Labels: enhancement, testing

#28 Testit
  kontaktilomake/templates/index.html
  kontaktilomake/tests/test_views_models.py
  uutiset/management/commands/seed.py
  uutiset/templates/uutinen_detail.html
  uutiset/templates/uutiset.html
Labels: testing
